---
- hosts: localhost
  tasks:
  - name: 'Checking required parameters'
    assert:
      that:
      - stack_path is defined
      - copy_path is defined
      - copy_once is defined

- hosts: "{% if copy_labels is defined %}{{ copy_labels | dict2items | json_query('[].[key, value]') | map('join', '_') | list | join(':&') }}{% else %}all{% endif %}"
  run_once: "{{ copy_once | bool }}"
  tasks:
  - name: "Ensuring target path {{ copy_path }} exists"
    file:
      path: "{{ copy_path }}"
      state: directory

  - name: "Synchronizing files"
    loop: "{{ copy_sources | default([]) }}"
    synchronize:
      archive: false
      use_ssh_args: true
      src: "{{ stack_path }}/"
      dest: "{{ copy_path }}/"
      rsync_opts:
      - "--include={{ item }}"
      - "--exclude=*"
